import {redirect} from "next/navigation";
import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {createWorkOrder,scheduleWorkOrder,assignWorkOrder,startWorkOrder,completeWorkOrder} from "./actions";

export default async function Page(){
 const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect("/login");
 const [{data:rows},{data:props},{data:crews},{data:emps},{data:cons},{data:eq}]=await Promise.all([
  s.from("work_orders").select("id,work_order_number,property_id,priority,status,scheduled_start,scheduled_end,description").order("scheduled_start",{ascending:true,nullsFirst:false}).limit(200),
  s.from("properties").select("id,name").order("name"),s.from("crews").select("id,name").eq("status","active").order("name"),
  s.from("employees").select("id,first_name,last_name").eq("employment_status","active").order("last_name"),
  s.from("contractors").select("id,organization_id").eq("status","active").limit(100),
  s.from("equipment").select("id,name,asset_number").eq("status","available").order("name")
 ]);
 return <main className="list-shell"><header className="list-header"><div><Link className="back" href="/dashboard">← Command</Link><span className="eyebrow">FIELD OPERATIONS</span><h1>Work orders</h1></div><Link href="/dispatch" className="button">Dispatch board</Link></header>
 <section className="table-panel"><h2>Create</h2><form action={createWorkOrder} className="form-grid"><select name="property_id" required><option value="">Property</option>{props?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name="priority"><option>normal</option><option>low</option><option>high</option><option>urgent</option><option>emergency</option></select><input name="scheduled_start" type="datetime-local"/><input name="scheduled_end" type="datetime-local"/><input name="estimated_duration_minutes" type="number" min="1" placeholder="Duration (min)"/><input name="description" required placeholder="Description"/><input name="site_instructions" placeholder="Site instructions"/><button>Create work order</button></form></section>
 <section className="table-panel"><div className="table-wrap"><table><thead><tr><th>WO</th><th>Property</th><th>Status</th><th>Schedule</th><th>Priority</th><th>Dispatch</th></tr></thead><tbody>{rows?.map(r=><tr key={r.id}><td>{r.work_order_number}</td><td>{props?.find(p=>p.id===r.property_id)?.name??"—"}</td><td>{r.status}</td><td>{r.scheduled_start??"—"}</td><td>{r.priority}</td><td>
 <form action={scheduleWorkOrder} className="actions"><input type="hidden" name="id" value={r.id}/><input name="scheduled_start" type="datetime-local" required/><button>Schedule</button></form>
 <div className="actions"><form action={assignWorkOrder}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="assignment_type" value="crew"/><select name="resource_id" required><option value="">Crew</option>{crews?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button>Assign crew</button></form><form action={assignWorkOrder}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="assignment_type" value="employee"/><select name="resource_id" required><option value="">Employee</option>{emps?.map(x=><option key={x.id} value={x.id}>{x.first_name} {x.last_name}</option>)}</select><button>Assign employee</button></form></div>
 <div className="actions"><form action={assignWorkOrder}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="assignment_type" value="contractor"/><select name="resource_id" required><option value="">Contractor</option>{cons?.map(x=><option key={x.id} value={x.id}>Organization {x.organization_id}</option>)}</select><button>Assign contractor</button></form><form action={assignWorkOrder}><input type="hidden" name="id" value={r.id}/><input type="hidden" name="assignment_type" value="equipment"/><select name="resource_id" required><option value="">Equipment</option>{eq?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button>Assign equipment</button></form></div>
 {["scheduled","assigned","en_route"].includes(r.status)&&<form action={startWorkOrder}><input type="hidden" name="id" value={r.id}/><button>Start</button></form>}{r.status==="in_progress"&&<form action={completeWorkOrder}><input type="hidden" name="id" value={r.id}/><button>Complete</button></form>}
 </td></tr>)}</tbody></table></div></section></main>
}