insert into public.contacts(workspace_id,first_name,last_name,job_title,email,phone,status,notes,source_url,source_label,source_confidence,source_verified_at)
select o.workspace_id,'Ryan','Murphy','Asset Manager','rmurphy@huntingtonproperties.ca','613-592-1818 ext. 31','active','Current Huntington Properties staff directory. Asset Manager. Source: https://huntingtonproperties.ca/our-team/','https://huntingtonproperties.ca/our-team/','Huntington Properties official team directory','high',now()
from public.organizations o where o.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and coalesce(o.operating_name,o.legal_name)='Huntington Properties' and not exists(select 1 from public.contacts c where c.workspace_id=o.workspace_id and c.first_name='Ryan' and c.last_name='Murphy');
insert into public.contacts(workspace_id,first_name,last_name,job_title,email,phone,status,notes,source_url,source_label,source_confidence,source_verified_at)
select o.workspace_id,'Shawn','Fensel','Construction Project Manager','sfensel@huntingtonproperties.ca','613-592-1818 ext. 31','active','Current Huntington Properties staff directory. Construction Project Manager. Source: https://huntingtonproperties.ca/our-team/','https://huntingtonproperties.ca/our-team/','Huntington Properties official team directory','high',now()
from public.organizations o where o.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and coalesce(o.operating_name,o.legal_name)='Huntington Properties' and not exists(select 1 from public.contacts c where c.workspace_id=o.workspace_id and c.first_name='Shawn' and c.last_name='Fensel');
insert into public.contacts(workspace_id,first_name,last_name,job_title,email,phone,status,notes,source_url,source_label,source_confidence,source_verified_at)
select o.workspace_id,'Janet','Wlodarczyk','Director of Finance and Administration','jwlodarczyk@elmwood.ca','613-749-6761 ext. 223','active','Elmwood official volunteer page gives direct contact details for finance and administration questions. Source: https://www.elmwood.ca/parents/volunteering','https://www.elmwood.ca/parents/volunteering','Elmwood School official volunteer/contact page','high',now()
from public.organizations o where o.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and coalesce(o.operating_name,o.legal_name)='Elmwood School' and not exists(select 1 from public.contacts c where c.workspace_id=o.workspace_id and c.first_name='Janet' and c.last_name='Wlodarczyk');
insert into public.contacts(workspace_id,first_name,last_name,job_title,email,phone,status,notes,source_url,source_label,source_confidence,source_verified_at)
select o.workspace_id,'Katrin','Spencer','Vice-President, Strategy and Business Development','kspencer@perleyhealth.ca',null,'active','Current Perley Health strategic planning page identifies Katrin Spencer as Vice-President, Strategy and Business Development and gives her direct email for strategic planning questions. Source: https://www.perleyhealth.ca/strategic-planning-2025','https://www.perleyhealth.ca/strategic-planning-2025','Perley Health strategic planning page','high',now()
from public.organizations o where o.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and coalesce(o.operating_name,o.legal_name)='Perley Health' and not exists(select 1 from public.contacts c where c.workspace_id=o.workspace_id and c.first_name='Katrin' and c.last_name='Spencer');
insert into public.contacts(workspace_id,first_name,last_name,job_title,email,phone,status,notes,source_url,source_label,source_confidence,source_verified_at)
select o.workspace_id,'Thango','Vu','Chief Financial Officer',null,null,'active','Ashbury College current 2026 leadership page identifies Thango Vu as Chief Financial Officer. No direct contact details published on the source page; email intentionally left blank.','https://ashbury.ca/about-us/','Ashbury College leadership page','high',now()
from public.organizations o where o.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and coalesce(o.operating_name,o.legal_name)='Ashbury College' and not exists(select 1 from public.contacts c where c.workspace_id=o.workspace_id and c.first_name='Thango' and c.last_name='Vu');
insert into public.organization_contacts(workspace_id,organization_id,contact_id,relationship_type,is_primary)
select o.workspace_id,o.id,c.id,'asset_management',false from public.organizations o join public.contacts c on c.workspace_id=o.workspace_id and c.first_name='Ryan' and c.last_name='Murphy' where coalesce(o.operating_name,o.legal_name)='Huntington Properties' and not exists(select 1 from public.organization_contacts x where x.organization_id=o.id and x.contact_id=c.id);
insert into public.organization_contacts(workspace_id,organization_id,contact_id,relationship_type,is_primary)
select o.workspace_id,o.id,c.id,'capital_projects',false from public.organizations o join public.contacts c on c.workspace_id=o.workspace_id and c.first_name='Shawn' and c.last_name='Fensel' where coalesce(o.operating_name,o.legal_name)='Huntington Properties' and not exists(select 1 from public.organization_contacts x where x.organization_id=o.id and x.contact_id=c.id);
insert into public.organization_contacts(workspace_id,organization_id,contact_id,relationship_type,is_primary)
select o.workspace_id,o.id,c.id,'finance_administration',false from public.organizations o join public.contacts c on c.workspace_id=o.workspace_id and c.first_name='Janet' and c.last_name='Wlodarczyk' where coalesce(o.operating_name,o.legal_name)='Elmwood School' and not exists(select 1 from public.organization_contacts x where x.organization_id=o.id and x.contact_id=c.id);
insert into public.organization_contacts(workspace_id,organization_id,contact_id,relationship_type,is_primary)
select o.workspace_id,o.id,c.id,'strategy_business_development',false from public.organizations o join public.contacts c on c.workspace_id=o.workspace_id and c.first_name='Katrin' and c.last_name='Spencer' where coalesce(o.operating_name,o.legal_name)='Perley Health' and not exists(select 1 from public.organization_contacts x where x.organization_id=o.id and x.contact_id=c.id);
insert into public.organization_contacts(workspace_id,organization_id,contact_id,relationship_type,is_primary)
select o.workspace_id,o.id,c.id,'finance',false from public.organizations o join public.contacts c on c.workspace_id=o.workspace_id and c.first_name='Thango' and c.last_name='Vu' where coalesce(o.operating_name,o.legal_name)='Ashbury College' and not exists(select 1 from public.organization_contacts x where x.organization_id=o.id and x.contact_id=c.id);
insert into public.property_contacts(workspace_id,property_id,contact_id,relationship_type,is_primary,emergency_contact,notes)
select p.workspace_id,p.id,c.id,'facilities_governance',false,false,'Elmwood leadership page identifies Simon Nehme as Board Vice-Chair and Chair of the Facilities Committee. Source: https://www.elmwood.ca/about/leadership'
from public.properties p join public.contacts c on c.workspace_id=p.workspace_id and c.first_name='Simon' and c.last_name='Nehme'
where p.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and p.owner_organization_id=(select id from public.organizations where workspace_id=p.workspace_id and coalesce(operating_name,legal_name)='Elmwood School') and not exists(select 1 from public.property_contacts x where x.property_id=p.id and x.contact_id=c.id);
