-- Expand verified property intelligence beyond the initial six seed properties.
-- Safe to rerun: all inserts resolve by workspace + canonical name/address and skip existing rows.
create temporary table tmp_property_seed(
name text,address_line_1 text,city text,province text,postal_code text,property_type text,owner_name text,
building_count integer,grounds_scope text,snow_scope text,janitorial_scope text,capital_projects_signal text,
vendor_signal text,procurement_signal text,seasonal_priority text,access_complexity text,liability_signal text,
intelligence_score numeric,summary text,source_url text,source_label text
) on commit drop;

insert into tmp_property_seed values
('570 Laurier','570 Laurier Avenue West','Ottawa','ON','K1R 1C8','condominium','570 Laurier — OCSCC 678',1,'common-element residential grounds','common-element service contract route','common-area cleaning; superintendent on site',null,'Apollo Property Management manages the corporation','board + property manager service-contract route',null,'downtown residential tower; pool and patio amenities','pool/common areas',84,'Condominium with identified property manager, board email, superintendent and common-element repair route.','https://570laurier.com/contact/','570 Laurier official contact page'),
('Somerset Gardens','138 Somerset St West','Ottawa','ON',null,'condominium','Somerset Gardens — OCSCC 795',1,'urban residential common grounds','board-managed/common-element service scope','common-element maintenance and building services',null,'Condominium Management Group manages the property','board vendor-selection route',null,'urban downtown/Golden Triangle property','residential common areas',82,'Condominium community with named board, property manager and dedicated board email; common-element maintenance is routed through management.','https://somersetgardens.ca/download/472/?tmstv=1701522806','Somerset Gardens resident newsletter'),
('Glebe Centre','77 Monk St','Ottawa','ON','K1S 5A7','healthcare_ltc','Glebe Centre',2,'campus grounds supporting long-term care','institutional snow/grounds scope','24/7 long-term-care environment','two LTC buildings: two-storey 1996 and six-storey 2004; 254 residents','facility operations / administration','institutional procurement route',null,'two attached LTC buildings on campus','24/7 care environment',91,'Long-term-care campus with two attached care buildings and 254 residents; operational continuity makes exterior and facility services high-consequence.','https://glebecentre.ca/wp-content/uploads/2024/07/Resident-Handbook-June-25-2024.pdf','Glebe Centre resident handbook'),
('CHEO Main Campus','401 Smyth Road','Ottawa','ON','K1H 8L1','healthcare','Children’s Hospital of Eastern Ontario',1,'large hospital campus grounds','institutional snow/grounds scope','hospital-grade environmental services/procurement route','10-year Smyth campus transformation plan','Strategic Sourcing / Facilities route','formal healthcare procurement; strategic sourcing',null,'large active hospital campus with construction activity','hospital/public-facing campus',94,'Main CHEO campus with 142 budgeted beds and an active long-term campus transformation program.','https://www.cheo.on.ca/en/about-us/cheo-data.aspx','CHEO official data and campus page'),
('Perley Health Campus','1750 Russell Road','Ottawa','ON','K1G 5Z6','healthcare_ltc','Perley Health',1,'large care-community grounds and outdoor areas','institutional winter maintenance','care-community cleaning and facility services','approved 120-bed LTC expansion; site-plan approval granted in 2026','facilities/development vendor route','active capital-project procurement environment','winter','multi-building care campus','600+ seniors/veterans; active construction/planning environment',95,'Large seniors/veterans care campus with site-plan approval for a new 120-bed LTC residence and ongoing development activity.','https://www.perleyhealth.ca/expansion','Perley Health expansion project'),
('Ashbury College Campus','362 Mariposa Avenue','Ottawa','ON','K1M 0T3','education','Ashbury College',1,'school campus grounds and sports/outdoor areas','school campus winter maintenance','campus janitorial/facilities services','active campus operations','school administration/facilities route','private-school vendor route','winter','active school campus with student/public access','student/family campus',82,'Private school campus with documented address and facilities footprint; direct campus operations route should be identified.','https://ashbury.ca/','Ashbury College official site'),
('Elmwood School Campus','261 Buena Vista Road','Ottawa','ON','K1M 0V9','education','Elmwood School',1,'school campus grounds','school campus winter maintenance','campus janitorial/facilities services','active school operations','school administration/facilities route','private-school vendor route','winter','active school campus','student/family campus',81,'Private girls school campus with documented address and direct administration contact.','https://www.elmwood.ca/admissions/admissions-2026','Elmwood School official admissions page'),
('Jami Omar Mosque','3990 Old Richmond Road','Nepean','ON','K2H 8R5','religious','Jami Omar Mosque',1,'large religious/community grounds','winter parking and grounds maintenance','community facility cleaning','ongoing facility programming and community use','facility administration / mosque management','direct institutional vendor route','winter','large community facility with gymnasium and parking','public-facing religious/community facility',83,'Large mosque/community facility with gymnasium, fitness centre, parking and recurring community programming.','https://www.jamiomar.org/','Jami Omar official site'),
('318-320 Richmond Road','318-320 Richmond Road','Ottawa','ON',null,'commercial','Huntington Properties',1,'commercial property grounds','commercial winter maintenance','commercial common-area cleaning','owner/developer portfolio','Huntington property management team','owner-operator vendor route','winter','urban office/retail site','commercial public-facing property',78,'Huntington-owned/managed commercial portfolio property listed on the official portfolio page.','https://huntingtonproperties.ca/property-portfolio-2/','Huntington Properties portfolio'),
('1120 Morrison Drive','1120 Morrison Drive','Ottawa','ON',null,'commercial','Huntington Properties',1,'commercial/industrial grounds','commercial winter maintenance','commercial common-area cleaning','owner/developer portfolio','Huntington property management team','owner-operator vendor route','winter','industrial/commercial site','commercial/industrial property',79,'Huntington-owned/managed portfolio property listed on the official portfolio page.','https://huntingtonproperties.ca/property-portfolio-2/','Huntington Properties portfolio'),
('2090 Robertson Road','2090 Robertson Road','Ottawa','ON',null,'commercial','Huntington Properties',1,'commercial/retail grounds','commercial winter maintenance','commercial common-area cleaning','owner/developer portfolio','Huntington property management team','owner-operator vendor route','winter','retail/commercial site','public-facing commercial property',80,'Huntington-owned/managed portfolio property listed on the official portfolio page.','https://huntingtonproperties.ca/property-portfolio-2/','Huntington Properties portfolio');

insert into public.properties(workspace_id,name,address_line_1,city,province,postal_code,country,property_type,status,owner_organization_id,primary_customer_organization_id,management_organization_id)
select '431aa13d-3e7c-41e3-9686-e840b8ea5b7c'::uuid,s.name,s.address_line_1,s.city,s.province,s.postal_code,'Canada',s.property_type,'prospect'::property_status,o.id,o.id,o.id
from tmp_property_seed s join public.organizations o on o.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and coalesce(o.operating_name,o.legal_name)=s.owner_name
where not exists(select 1 from public.properties p where p.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and p.name=s.name and p.address_line_1=s.address_line_1);

insert into public.property_intelligence(workspace_id,property_id,building_count,property_class,ownership_type,grounds_scope,snow_scope,janitorial_scope,capital_projects_signal,vendor_signal,procurement_signal,seasonal_priority,access_complexity,liability_signal,intelligence_score,intelligence_summary,primary_source_url,primary_source_label,data_confidence,verified_at)
select '431aa13d-3e7c-41e3-9686-e840b8ea5b7c'::uuid,p.id,s.building_count,s.property_type,'institution_or_owner_operator',s.grounds_scope,s.snow_scope,s.janitorial_scope,s.capital_projects_signal,s.vendor_signal,s.procurement_signal,s.seasonal_priority,s.access_complexity,s.liability_signal,s.intelligence_score,s.summary,s.source_url,s.source_label,'high',now()
from public.properties p join tmp_property_seed s on s.name=p.name and s.address_line_1=p.address_line_1
where p.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and not exists(select 1 from public.property_intelligence pi where pi.property_id=p.id);

insert into public.property_intelligence_sources(workspace_id,property_id,source_type,source_url,source_title,summary,confidence)
select p.workspace_id,p.id,'official_website',s.source_url,s.source_label,s.summary,'high'
from public.properties p join tmp_property_seed s on s.name=p.name and s.address_line_1=p.address_line_1
where p.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and not exists(select 1 from public.property_intelligence_sources x where x.property_id=p.id and x.source_url=s.source_url);

insert into public.outreach_target_properties(workspace_id,outreach_target_id,property_id,relationship_type,is_primary)
select t.workspace_id,t.id,p.id,case when p.property_type='condominium' then 'board_site' when p.property_type in ('healthcare','healthcare_ltc','education','religious') then 'facility_site' else 'owned_or_managed_site' end,true
from public.outreach_targets t join public.properties p on p.workspace_id=t.workspace_id and t.organization_id=p.owner_organization_id
where t.workspace_id='431aa13d-3e7c-41e3-9686-e840b8ea5b7c' and p.name in(select name from tmp_property_seed)
and not exists(select 1 from public.outreach_target_properties x where x.outreach_target_id=t.id and x.property_id=p.id);